// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoDDaIP1mf16Zpz8V7D_jzUq5JlMNwRAE',
    appId: '1:451698451970:android:f04e3de978c6fb48b2691b',
    messagingSenderId: '451698451970',
    projectId: 'flutter-prep-3407f',
    databaseURL: 'https://flutter-prep-3407f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-3407f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8CCV2Nnu4pImQdo67fLr7AN87QUmVOM',
    appId: '1:451698451970:ios:d226637098baec1eb2691b',
    messagingSenderId: '451698451970',
    projectId: 'flutter-prep-3407f',
    databaseURL: 'https://flutter-prep-3407f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-3407f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADn-oSiO6bUHURERoKgdUz_cv4ZN_ovII',
    appId: '1:451698451970:web:2bf1f97c0fc95636b2691b',
    messagingSenderId: '451698451970',
    projectId: 'flutter-prep-3407f',
    authDomain: 'flutter-prep-3407f.firebaseapp.com',
    databaseURL: 'https://flutter-prep-3407f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-3407f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADn-oSiO6bUHURERoKgdUz_cv4ZN_ovII',
    appId: '1:451698451970:web:ac94182f5e9bb1fab2691b',
    messagingSenderId: '451698451970',
    projectId: 'flutter-prep-3407f',
    authDomain: 'flutter-prep-3407f.firebaseapp.com',
    databaseURL: 'https://flutter-prep-3407f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-3407f.firebasestorage.app',
  );
}
